### ISSUE TITLE
plz help!!!!whyyyyyy

### ISSUE THREAD

**Issue by moyuuu0729** [cheesits456/Number-Guesser#3]
$ npm start

> number-guesser@1.0.0 start
> npm run build && node dist/index.js

> number-guesser@1.0.0 build
> rm -rf dist && ./node_modules/typescript/bin/tsc

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cheesits456** [comment]
This was made for linux, I forgot windows handles commands differently
